# Form implementation generated from reading ui file 'charWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6.QtCore import QTimer, Qt
from PyQt6.QtGui import QIcon, QColor
from qframelesswindow import FramelessWindow
from PyQt6 import QtCore, QtGui, QtWidgets
from qfluentwidgets import ImageLabel, MessageBoxBase, LineEdit


# class ChatBubble(QWidget):
#     def __init__(self, text, is_sender):
#         super().__init__()
#         self.text = text
#         self.is_sender = is_sender
#         self.initUI()
#
#     def initUI(self):
#         self.setMinimumHeight(50)
#         self.setMaximumWidth(300)
#
#     def paintEvent(self, event):
#         painter = QPainter(self)
#         painter.setRenderHint(QPainter.RenderHint.Antialiasing)
#
#         if self.is_sender:
#             painter.setBrush(QColor(173, 216, 230))
#             painter.drawRoundedRect(10, 10, self.width() - 20, self.height() - 20, 10, 10)
#         else:
#             painter.setBrush(QColor(240, 240, 240))
#             painter.drawRoundedRect(10, 10, self.width() - 20, self.height() - 20, 10, 10)
#
#         painter.setPen(QColor(0, 0, 0))
#         painter.setFont(QFont('Arial', 10))
#         painter.drawText(20, 30, self.text)


class Avatar(QtWidgets.QLabel):
    def __init__(self, avatar, parent=None):
        super().__init__(parent)
        if isinstance(avatar, str):
            self.setPixmap(QtGui.QPixmap(avatar).scaled(45, 45))
            self.image_path = avatar
        elif isinstance(avatar, QtGui.QPixmap):
            self.setPixmap(avatar.scaled(45, 45))
        self.setFixedSize(QtCore.QSize(45, 45))


class Triangle(QtWidgets.QLabel):
    def __init__(self, Type, is_send=False, parent=None):
        super().__init__(parent)
        self.Type = Type
        self.is_send = is_send
        self.setFixedSize(6, 45)

    def paintEvent(self, a0: QtGui.QPaintEvent) -> None:
        super().paintEvent(a0)
        painter = QtGui.QPainter(self)
        triangle = QtGui.QPolygon()
        if self.Type == "Text":
            if self.is_send:
                painter.setPen(QtGui.QColor('#b2e281'))
                painter.setBrush(QtGui.QColor('#b2e281'))
                triangle.setPoints(0, 20, 0, 35, 6, 25)
            else:
                painter.setPen(QtGui.QColor('white'))
                painter.setBrush(QtGui.QColor('white'))
                triangle.setPoints(0, 25, 6, 20, 6, 35)
            painter.drawPolygon(triangle)


class TextMessage(QtWidgets.QLabel):
    heightSignal = QtCore.pyqtSignal(int)

    def __init__(self, text, is_send=False, parent=None):
        super().__init__(text, parent)
        self.setFont(QtGui.QFont('微软雅黑', 12))
        self.setWordWrap(True)
        self.setMaximumWidth(800)
        self.setMinimumWidth(100)
        self.setMinimumHeight(35)
        self.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.setSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        if is_send:
            self.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter | QtCore.Qt.AlignmentFlag.AlignRight)
            self.setStyleSheet(
                '''
                background-color:#b2e281;
                border-radius:15px;
                border-top: 5px solid #b2e281;
                border-bottom: 5px solid #b2e281;
                border-right: 10px solid #b2e281;
                border-left: 10px solid #b2e281;
                '''
            )
        else:
            self.setStyleSheet(
                '''
                background-color:white;
                border-radius:15px;
                border-top: 5px solid white;
                border-bottom: 5px solid white;
                border-right: 10px solid white;
                border-left: 10px solid white;
                '''
            )
        w = len(text) * 16 + 30
        if w < self.width():
            self.setMaximumWidth(w)

# class Imagemessage(ImageLabel):

class BubbleMessage(QtWidgets.QWidget):
    def __init__(self, str_content, avatar_path, Type, is_send=False, widget=None, parent=None):
        super().__init__(parent)
        self.isSend = is_send
        self.setStyleSheet('border:none;')
        layout = QtWidgets.QHBoxLayout()
        layout.setSpacing(0)
        layout.setContentsMargins(0, 5, 5, 5)
        self.avatar = AvatarWidget(avatar_path)
        self.avatar.setRadius(18)
        triangle = Triangle(Type, is_send)
        if Type == "Text":
            self.message = TextMessage(str_content, is_send)
        elif Type == "Co_Invite":
            self.message = widget
        else:
            raise ValueError("未知的消息类型")

        self.spacerItem = QtWidgets.QSpacerItem(45 + 6, 45, QtWidgets.QSizePolicy.Policy.Expanding,
                                                QtWidgets.QSizePolicy.Policy.Minimum)
        if is_send:
            layout.addItem(self.spacerItem)
            layout.addWidget(self.message, 1)
            layout.addWidget(triangle, 0, QtCore.Qt.AlignmentFlag.AlignTop | QtCore.Qt.AlignmentFlag.AlignLeft)
            layout.addWidget(self.avatar, 0, QtCore.Qt.AlignmentFlag.AlignTop | QtCore.Qt.AlignmentFlag.AlignLeft)
        else:
            layout.addWidget(self.avatar, 0, QtCore.Qt.AlignmentFlag.AlignTop | QtCore.Qt.AlignmentFlag.AlignRight)
            layout.addWidget(triangle, 0, QtCore.Qt.AlignmentFlag.AlignTop | QtCore.Qt.AlignmentFlag.AlignRight)
            layout.addWidget(self.message, 1)
            layout.addItem(self.spacerItem)
        self.setLayout(layout)


class Chat_Window(FramelessWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        # Form.resize(611, 450)
        Form.setFixedSize(611, 450)
        self.scrollArea = ScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 60, 611, 291))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet('''border-bottom:none;''')
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.messages = QtWidgets.QListWidget(parent=self.scrollAreaWidgetContents)
        # self.messages.setGeometry(QtCore.QRect(-10, 0, 621, 281))
        # self.messages.setObjectName("messages")
        # self.apart_line = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        # self.apart_line.setGeometry(QtCore.QRect(0, 280, 621, 16))
        # self.apart_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        # self.apart_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        # self.apart_line.setObjectName("apart_line")
        self.scrollAreaLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.imageButton = TransparentToolButton(FluentIcon.IMAGE_EXPORT, parent=Form)
        self.imageButton.setGeometry(QtCore.QRect(580, 30, 31, 31))
        self.imageButton.setObjectName("imageButton")
        self.voice_chat = TransparentToolButton(FluentIcon.CHAT, parent=Form)
        self.voice_chat.setGeometry(QtCore.QRect(550, 30, 31, 31))
        self.voice_chat.setObjectName("voice_chat")
        self.file = TransparentToolButton(QIcon(r"icon/file.ico"), parent=Form)
        self.file.setGeometry(QtCore.QRect(520, 30, 31, 31))
        self.file.setObjectName("file")
        self.history = TransparentToolButton(FluentIcon.HISTORY, parent=Form)
        self.history.setGeometry(QtCore.QRect(460, 30, 31, 31))
        self.history.setObjectName("history")
        self.send = TransparentToolButton(FluentIcon.SEND, parent=Form)
        self.send.setGeometry(QtCore.QRect(570, 350, 51, 41))
        self.send.setObjectName("send")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 350, 571, 101))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollArea_2.setStyleSheet('''border:none;''')
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 569, 99))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.input_message = PlainTextEdit(parent=self.scrollAreaWidgetContents_2)
        self.input_message.setGeometry(QtCore.QRect(0, 0, 571, 101))
        self.input_message.setObjectName("input_message")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.avatar_main = AvatarWidget(parent=Form)
        self.avatar_main.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.avatar_main.setObjectName("avatar_main")
        self.chater_name = SubtitleLabel(parent=Form)
        # self.chater_name.setTextColor(QColor(0,255,255))
        self.chater_name.setGeometry(QtCore.QRect(100, 20, 150, 50))
        self.chater_name.setObjectName("chater_name")
        self.sight_chat = TransparentToolButton(QIcon(r"icon/Video_chat.ico"), parent=Form)
        self.sight_chat.setGeometry(QtCore.QRect(490, 30, 31, 31))
        self.sight_chat.setObjectName("sight_chat")
        self.CoWork = TransparentToolButton(QIcon(r"icon/cowork.png"), parent=Form)
        self.CoWork.setGeometry(QtCore.QRect(430, 30, 31, 31))
        self.CoWork.setObjectName("sight_chat")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.imageButton.setText(_translate("Form", ""))
        self.voice_chat.setText(_translate("Form", ""))
        self.file.setText(_translate("Form", ""))
        self.send.setText(_translate("Form", ""))
        self.avatar_main.setText(_translate("Form", ""))
        self.sight_chat.setText(_translate("Form", ""))
        self.CoWork.setText(_translate("Form", ""))


class CustomMessageBox(MessageBoxBase):
    """ Custom message box """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.titleLabel = SubtitleLabel('打开 URL')
        self.urlLineEdit = LineEdit()

        self.urlLineEdit.setPlaceholderText('输入文件、流或者播放列表的 URL')
        self.urlLineEdit.setClearButtonEnabled(True)

        # 将组件添加到布局中
        self.viewLayout.addWidget(self.titleLabel)
        self.viewLayout.addWidget(self.urlLineEdit)

        # 设置对话框的最小宽度
        self.widget.setMinimumWidth(350)


from qfluentwidgets import AvatarWidget, PlainTextEdit, ScrollArea, TransparentToolButton, FluentIcon, BodyLabel, \
    TitleLabel, SubtitleLabel

if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    window = Chat_Window()
    window.show()
    app.exec()
