# Form implementation generated from reading ui file 'mainlist.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import json

from PyQt6 import QtCore, QtGui, QtWidgets
from qframelesswindow import FramelessWindow
from ui.charWindow import Chat_Window


class Ui_mainList(FramelessWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        # self.chat_windows = {}

    def setupUi(self, mainList):
        mainList.setObjectName("mainList")
        mainList.setFixedSize(374, 758)
        mainList.move(1100,50)
        self.avatar = AvatarWidget(parent=mainList)
        self.avatar.setGeometry(QtCore.QRect(10, 40, 61, 41))
        self.avatar.setObjectName("avatar")
        self.scrollArea = ScrollArea(parent=mainList)
        self.scrollArea.setGeometry(QtCore.QRect(0, 129, 374, 631))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 374, 629))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.FriendlistWidget = ListWidget(parent=self.scrollAreaWidgetContents)
        self.FriendlistWidget.setGeometry(QtCore.QRect(0, 0, 374, 631))
        self.FriendlistWidget.setObjectName("FriendlistWidget")

        self.FriendlistWidget.itemDoubleClicked.connect(self.to_chatwindow)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(mainList)
        QtCore.QMetaObject.connectSlotsByName(mainList)

    def retranslateUi(self, mainList):
        _translate = QtCore.QCoreApplication.translate
        mainList.setWindowTitle(_translate("mainList", "Form"))
        self.avatar.setText(_translate("mainList", "TextLabel"))



from qfluentwidgets import AvatarWidget, ListWidget, ScrollArea

