# Form implementation generated from reading ui file 'registe.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import json

from PyQt6 import QtCore, QtGui, QtWidgets
from qframelesswindow import FramelessWindow


class RegisteWindow(FramelessWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Registe):
        Registe.setObjectName("Registe")
        Registe.setFixedSize(500, 260)
        self.label = QtWidgets.QLabel(parent=Registe)
        self.label.setGeometry(QtCore.QRect(70, 60, 51, 31))
        self.label.setStyleSheet("font-size:18px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Registe)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 51, 21))
        self.label_2.setStyleSheet("font-size:18px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Registe)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 81, 21))
        self.label_3.setStyleSheet("font-size:18px;")
        self.label_3.setObjectName("label_3")
        self.username = LineEdit(parent=Registe)
        self.username.setGeometry(QtCore.QRect(150, 60, 231, 31))
        self.username.setObjectName("username")
        self.confirm_psd = LineEdit(parent=Registe)
        self.confirm_psd.setGeometry(QtCore.QRect(150, 160, 231, 31))
        self.confirm_psd.setObjectName("confirm_psd")
        self.password = LineEdit(parent=Registe)
        self.password.setGeometry(QtCore.QRect(150, 110, 231, 31))
        self.password.setObjectName("password")
        self.pushButton = PushButton(parent=Registe)
        self.pushButton.setGeometry(QtCore.QRect(330, 210, 91, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Registe)
        QtCore.QMetaObject.connectSlotsByName(Registe)

    def retranslateUi(self, Registe):
        _translate = QtCore.QCoreApplication.translate
        Registe.setWindowTitle(_translate("Registe", "Form"))
        self.label.setText(_translate("Registe", "昵称"))
        self.label_2.setText(_translate("Registe", "密码"))
        self.label_3.setText(_translate("Registe", "确认密码"))
        self.pushButton.setText(_translate("Registe", "注册"))


from qfluentwidgets import LineEdit, PushButton

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = RegisteWindow()
    window.show()
    sys.exit(app.exec())