# Form implementation generated from reading ui file 'add_friend_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from qframelesswindow import FramelessWindow


class add_friend_window(FramelessWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, add_friend_window):
        add_friend_window.setObjectName("add_friend_window")
        add_friend_window.setFixedSize(500, 471)
        add_friend_window.setStyleSheet('''
        background: rgba( 239, 243, 245, 1 );
box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
backdrop-filter: blur( 8px );
-webkit-backdrop-filter: blur( 8px );
border-radius: 10px;
border: 1px solid rgba( 255, 255, 255, 0.18 );
        ''')

        self.lineEdit = SearchLineEdit(parent=add_friend_window)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setGeometry(QtCore.QRect(75,50,350,50))

        self.scrollArea = ScrollArea(parent=add_friend_window)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setGeometry(QtCore.QRect(0, 120, 500, 351))
        self.scrollArea.setStyleSheet('''
        background: rgba( 255, 255, 255, 0.65 );
        box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
        backdrop-filter: blur( 8px );
        -webkit-backdrop-filter: blur( 8px );
        border-radius: 10px;
        border: 1px solid rgba( 255, 255, 255, 0.18 );
        ''')
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0,120,500,351))

        self.listWidget = ListWidget(parent=self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 500, 351))
        self.listWidget.setStyleSheet('''
        background: rgba( 110, 191, 223, 0.4 );
box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
backdrop-filter: blur( 8px );
-webkit-backdrop-filter: blur( 8px );
border-radius: 10px;
border: 1px solid rgba( 255, 255, 255, 0.18 );
''')
        self.listWidget.setObjectName("listWidget")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(add_friend_window)
        QtCore.QMetaObject.connectSlotsByName(add_friend_window)

    def retranslateUi(self, add_friend_window):
        _translate = QtCore.QCoreApplication.translate
        add_friend_window.setWindowTitle(_translate("add_friend_window", "Add Friend"))


from qfluentwidgets import ScrollArea, SearchLineEdit, ListWidget
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = add_friend_window()
    window.show()
    sys.exit(app.exec())